export const PROJEKAT_URL ='http://localhost:8080/projekat'
export const SMER_URL ='http://localhost:8080/smer'
export const GRUPA_URL ='http://localhost:8080/grupa'
export const STUDENT_URL ='http://localhost:8080/student'
export const STUDENTI_ZA_GRUPU_URL ='http://localhost:8080/studentByGrupaID'